name: Build

on:
  workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt install -y gcc-14 gcc-14-plugin-dev

    - name: Config Git
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com

    - name: Build
      run: make all

    - name: Commit and Push files
      run: |
        git add .
        git commit -m "Update Configs"
        git push
